name: BuildDockerImage

on:
  release:
    types: [created, edited]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump GITHUB REF
        run: echo "${GITHUB_REF}"
      - name: Build the Docker image
        run: docker build --build-arg BRANCH= . --file Dockerfile --tag my-image-name:$(date +%s)
